#
# Bare minimal configuration for safety developer practice
#
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--unsafe]


- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.2
  hooks:
    - id: gitleaks

# PYTHON LINTING
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args: ["-rn", "-sn", "--rcfile=pylintrc", "--fail-on=I"]
      exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/
